name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        ios: [17]
    name: Build on iOS (${{ matrix.ios }})
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$.app && /usr/bin/xcodebuild -version
      - name: Build Example App
        run: |
          xcodebuild -workspace ExampleSwiftUI/ExampleSwiftUI.xcodeproj/project.xcworkspace \
            -scheme ExampleSwiftUI \
            -sdk iphoneos build
