name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Example App
        run: |
          xcodebuild -workspace ExampleSwiftUI/ExampleSwiftUI.xcodeproj/project.xcworkspace \
            -scheme ExampleSwiftUI \
            -sdk iphoneos build
